### ISSUE TITLE
Magazine TOC - Control order of list

### ISSUE THREAD

**Issue by marycklein** [WesternFriend/westernfriend.org#1027]
Add some sort of field that would allow me to rank the order that articles will display on the page for an individual magazine issue.

I both . . .
- want to control the display order of the “featured” articles,
- and I want to control the display order within departments.

It would be fine if you added "time article published" widget to the "build magazine article" page, and told the display listing to present them in chronological order. As long as I could write the time in for each article.

**Comment by marycklein** [comment]
A fall-back plan could be to set things up so that, on a page that lists all articles in an individual magazine issue, within each department, the articles would be listed alphabetically by family name of first author.

**Comment by brylie** [comment]
We initially agreed on alphabetical sorting, since it is conventional and pragmatic.

Adding manual or author-based sorting would introduce a couple of challenges:

1. **Featured Articles**: We currently mark these directly on the article pages for easy publishing. Sorting them by position during editing would be cumbersome, requiring the editor to constantly switch between articles and remember their sort order.
2. **Sorting by Author's Last Name**: This approach has two drawbacks:
   - It's not intuitive for users, as articles are listed by title, not author. Sorting by the author would be confusing since it's not the primary information displayed.
   - Technically, this would increase page loading times and complexity. The server would have to process a lot more information, sorting articles by the first-listed author's last name, which could slow down the site and burden the server.

Given these issues, and our goal to simplify and speed up the website, I think these sorting methods might complicate things rather than help. I'm keen on maintaining our focus on enhancing user experience through simplicity and efficiency. 

Any thoughts on how we can address these sorting challenges without compromising our usability and performance?

**Comment by brylie** [comment]
Closing this since it is outside of the scope of what we can handle currently. It may also make the system more unstable by adding complexity as well.
