### ISSUE TITLE
Search results - possibly adjust reach

### ISSUE THREAD

**Issue by marycklein** [WesternFriend/westernfriend.org#1065]
Two adjustments to search results would be good, although I wonder if it's possible to aim for both at once. They seem to be at cross purposes.

1) it would be good that for a term like "Patricia Loring" to display top of the list ALL results that concern "Patricia Loring" and later in the list display results that concern other "Patricia" pages

2) it would be good if when searching for mistakenly for "Hoggat," when the correct spelling of the name is actually "Hoggatt," that results for "Hoggatt" would still come up. Obviously, this would pertain to many nouns searched in singular form when on the page they are listed with "s" on the end.

**Comment by brylie** [comment]
I've improved the indexing of our search code, so the results should now be more relevant overall.

Our search logic still operates using an "or" approach, where each term is treated individually. For example, searching "Patricia Loring" will return results containing either "Patricia" or "Loring." This is intentional, as it allows us to sort results by relevancy. It also works well for broader searches, like "how to promote world peace," where the engine can return results that include any combination of those words. 

If we used an "and" approach, the search would only return results containing every word ("how" AND "to" AND "promote" AND "world" AND "peace"), which could reduce the overall relevancy.

After some consideration and previous discussion, we've chosen to go with the "or" operator, which is also recommended by the Wagtail documentation:

> The search operator specifies how the search should behave when the user has typed in multiple search terms. There are two possible values:
>
> - “or” - The results must match at least one term (default for Elasticsearch)
> - “and” - The results must match all terms (default for database search)
>
> Both operators have benefits and drawbacks. The “or” operator will return many more results but will likely contain a lot of results that aren’t relevant. The “and” operator only returns results that contain all search terms but requires the user to be more precise with their query.
>
> We recommend using the “or” operator when ordering by relevance and the “and” operator when ordering by anything else.
>
> https://docs.wagtail.org/en/stable/topics/search/searching.html#search-operator

**Comment by brylie** [comment]
> it would be good if when searching for mistakenly for "Hoggat," when the correct spelling of the name is actually "Hoggatt," that results for "Hoggatt" would still come up. Obviously, this would pertain to many nouns searched in singular form when on the page they are listed with "s" on the end.

I've checked on this idea of "fuzzy matching," and it turns out we can't support fuzzy matching unless we switch our search database to Elasticsearch. At this point in the project lifecycle, where we are focusing mainly on practical maintenance, adding a new database component wouldn't seem practical.

> Fuzzy matching will return documents which contain terms similar to the search term, as measured by a [Levenshtein edit distance](https://en.wikipedia.org/wiki/Levenshtein_distance).
>
> Fuzzy matching is supported by the Elasticsearch search backend only.
>
> https://docs.wagtail.org/en/stable/topics/search/searching.html#fuzzy-matching

**Comment by marycklein** [comment]
Thank-you for these instructive messages!

Your reasoning is good all-around here.

Have a great weekend.

Best,
Mary

Mary Klein
Editor / Executive Director

Western Friend
2625 Middlefield Road, #565
Palo Alto, CA  94306-2516
650-318-1652

**Comment by brylie** [comment]
Closing after discussion with Mary
