### ISSUE TITLE
Indicate whether "users" are "subscribers"

### ISSUE THREAD

**Issue by marycklein** [WesternFriend/westernfriend.org#1095]
Is there any way to include in the list of information about "users" here
https://westernfriend.org/admin/users/?ordering=-is_superuser
Whether each one is an active "subscriber" to the magazine or not?

There are now five pages of entries and I need to figure out which ones still need to be set as subscribers manually by me -- because they paid offline.

**Comment by brylie** [comment]
We don’t store the subscription status (active or not) in our system since subscriptions are fully managed by PayPal. So it may not be possible to display that status for multiple users in a listing. 

Our code for pages like the magazine article actively checks with PayPal whether the user subscription is active whenever they view the page. However, the same check applied to multiple users on the user management page may cause issues when rendering the table like unexpected delays. 

This was a trade-off that was introduced when we switched from Braintree to PayPal where we didn’t have enough time or means to develop code that would fully synchronize the subscription statuses.

**Comment by brylie** [comment]
Check the Subscriptions page which lets you search by the user email and see their subscription status:

https://westernfriend.org/admin/subscriptions/

**Comment by marycklein** [comment]
Thanks for this explanation.

I’ll try to not ask this again!

Best,
Mary


Mary Klein
Editor / Executive Director

Western Friend
2625 Middlefield Road, #565
Palo Alto, CA  94306-2516
650-318-1652

**Comment by brylie** [comment]
We've now merged a new feature to export users including their email addresses, which can be compared with the list of subscriptions
