### ISSUE TITLE
Ability to export lists of "users" and "subscribers"

### ISSUE THREAD

**Issue by marycklein** [WesternFriend/westernfriend.org#1097]
Please set up some way for me to export CSV lists of our registered "users" and our "subscribers." 

I need to compare these two sets of data and they are getting too large for me to go through the two sets one item by one item by one item by one item . . . 

Thanks!!
mk

**Comment by brylie** [comment]
It turns out that modifying the Wagtail Users listing is not easy. I opened a feature request for this back in November of 2023, but there hasn't been any response:

https://github.com/wagtail/wagtail/issues/11255

**Comment by brylie** [comment]
I've updated the Subscriptions page to allow exporting subscription data:

<img width="731" alt="Screenshot 2024-07-09 at 16 05 29" src="https://github.com/WesternFriend/westernfriend.org/assets/17307/796d4629-019e-47ea-8bff-6a17e27299e1">

However, it turns out that modifying the Wagtail Users listing is not easy. I opened a feature request for this back in November of 2023, but there hasn't been any response:

https://github.com/wagtail/wagtail/issues/11255

So, I'm unsure how we would add an export button to the Wagtail users' listing currently.

**Comment by marycklein** [comment]
Thank-you! I apologize for not remembering that I’ve asked for the same change after we’ve already settled that it’s not possible. I realize this is not the first time I’ve done this. Thanks for your patience!
m

**Comment by brylie** [comment]
All good. Let me know if the new subscription export feature is helpful in any case.

It sounds like the Wagtail developers will fix the issue regarding customizing the Users listing soon, based on a recent response in the linked issue.
